baseURL = "https://walessong.github.io/"
languageCode = "en-us"
title = "Woke Soul"
buildFuture = true

[params]
  description = "Crypto Trader & Analyst exploring the intersection of quantitative patterns and literary aesthetics."
  # 首页头像：将图片放到 static/images/ 下，此处填路径，如 "images/avatar.jpg"
  avatar = ""

  [params.author]
    name = "Woke Soul"
    title = "Crypto Trader & Analyst | Patterns / Fractals | Machine Learning | Literature"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
